# Generated by Django 5.0.7 on 2024-08-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('reviewcontent', models.CharField(max_length=100)),
                ('ratings', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('reviewer_email_id', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('PU', 'Published'), ('NPU', 'Notpublished')], default='PU', max_length=4)),
            ],
        ),
    ]
