# Generated by Django 5.0.7 on 2024-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRSApp', '0002_mrsystem_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsystem',
            name='geners',
            field=models.CharField(choices=[('horror', 'HORROR'), ('action', 'ACTION'), ('scifi', 'SCI-FI'), ('comedy', 'COMEDY'), ('thriller', 'THRILLER')], max_length=15),
        ),
        migrations.AlterField(
            model_name='mrsystem',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('NotPublished', 'Notpublished')], default='Published', max_length=20),
        ),
    ]
